"""phase 2: memory, projects, knowledge

Revision ID: 4119c1cc8521
Revises: e915ec393404
Create Date: 2026-08-10 06:46:26.392925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4119c1cc8521'
down_revision: Union[str, Sequence[str], None] = 'e915ec393404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_kind', sa.String(length=48), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('norm', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings'))
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_embedding_model_owner', ['model', 'owner_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('uq_embedding_owner', ['owner_kind', 'owner_id', 'model'], unique=True)

    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_direction', sa.String(length=48), nullable=False),
    sa.Column('sync_status', sa.String(length=48), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_knowledge_sources_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sources'))
    )
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_sources_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_knowledge_source_user_key', ['user_id', 'key'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('current_state', sa.Text(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_project_user_key', ['user_id', 'key'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_kind', sa.String(length=48), nullable=False),
    sa.Column('uri', sa.String(length=2000), nullable=True),
    sa.Column('source_ref', sa.JSON(), nullable=True),
    sa.Column('media_type', sa.String(length=128), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('tainted', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_documents_project_id_projects')),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], name=op.f('fk_documents_source_id_knowledge_sources')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_document_source', ['source_kind', 'uri'], unique=False)
        batch_op.create_index('ix_document_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_source_kind'), ['source_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('source_ref', sa.JSON(), nullable=True),
    sa.Column('tainted', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('superseded_by', sa.String(length=64), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_memories_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_memory_project', ['project_id', 'status'], unique=False)
        batch_op.create_index('ix_memory_user_status_type', ['user_id', 'status', 'type'], unique=False)
        batch_op.create_index('ix_memory_user_subject', ['user_id', 'subject'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('heading_path', sa.String(length=1000), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_chunk_document_ordinal', ['document_id', 'ordinal'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('memory_links',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('from_memory_id', sa.String(length=64), nullable=False),
    sa.Column('to_memory_id', sa.String(length=64), nullable=False),
    sa.Column('relation', sa.String(length=48), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_memory_id'], ['memories.id'], name=op.f('fk_memory_links_from_memory_id_memories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_memory_id'], ['memories.id'], name=op.f('fk_memory_links_to_memory_id_memories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_links'))
    )
    with op.batch_alter_table('memory_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_links_from_memory_id'), ['from_memory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_links_to_memory_id'), ['to_memory_id'], unique=False)
        batch_op.create_index('uq_memlink', ['from_memory_id', 'to_memory_id', 'relation'], unique=True)

    op.create_table('memory_revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], name=op.f('fk_memory_revisions_memory_id_memories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_revisions'))
    )
    with op.batch_alter_table('memory_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_revisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_revisions_memory_id'), ['memory_id'], unique=False)
        batch_op.create_index('ix_memrev_memory_created', ['memory_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_revisions', schema=None) as batch_op:
        batch_op.drop_index('ix_memrev_memory_created')
        batch_op.drop_index(batch_op.f('ix_memory_revisions_memory_id'))
        batch_op.drop_index(batch_op.f('ix_memory_revisions_created_at'))

    op.drop_table('memory_revisions')
    with op.batch_alter_table('memory_links', schema=None) as batch_op:
        batch_op.drop_index('uq_memlink')
        batch_op.drop_index(batch_op.f('ix_memory_links_to_memory_id'))
        batch_op.drop_index(batch_op.f('ix_memory_links_from_memory_id'))

    op.drop_table('memory_links')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))
        batch_op.drop_index('ix_chunk_document_ordinal')

    op.drop_table('document_chunks')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index('ix_memory_user_subject')
        batch_op.drop_index('ix_memory_user_status_type')
        batch_op.drop_index('ix_memory_project')
        batch_op.drop_index(batch_op.f('ix_memories_user_id'))
        batch_op.drop_index(batch_op.f('ix_memories_type'))
        batch_op.drop_index(batch_op.f('ix_memories_status'))
        batch_op.drop_index(batch_op.f('ix_memories_source'))
        batch_op.drop_index(batch_op.f('ix_memories_project_id'))
        batch_op.drop_index(batch_op.f('ix_memories_expires_at'))
        batch_op.drop_index(batch_op.f('ix_memories_created_at'))

    op.drop_table('memories')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_source_kind'))
        batch_op.drop_index(batch_op.f('ix_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_documents_content_hash'))
        batch_op.drop_index('ix_document_user_status')
        batch_op.drop_index('ix_document_source')

    op.drop_table('documents')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('uq_project_user_key')
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_status'))

    op.drop_table('projects')
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.drop_index('uq_knowledge_source_user_key')
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_user_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_kind'))

    op.drop_table('knowledge_sources')
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index('uq_embedding_owner')
        batch_op.drop_index(batch_op.f('ix_embeddings_owner_id'))
        batch_op.drop_index(batch_op.f('ix_embeddings_model'))
        batch_op.drop_index('ix_embedding_model_owner')

    op.drop_table('embeddings')
    # ### end Alembic commands ###
