"""phase 3: computer actions and tasks

Revision ID: 6dfc55cb77e4
Revises: 4119c1cc8521
Create Date: 2026-08-10 09:56:33.724719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dfc55cb77e4'
down_revision: Union[str, Sequence[str], None] = '4119c1cc8521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computer_actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('applied_rules', sa.JSON(), nullable=False),
    sa.Column('confirmation_id', sa.String(length=64), nullable=True),
    sa.Column('confirmed_by', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('verification', sa.String(length=24), nullable=False),
    sa.Column('verification_detail', sa.Text(), nullable=True),
    sa.Column('observation_before', sa.String(length=64), nullable=True),
    sa.Column('observation_after', sa.String(length=64), nullable=True),
    sa.Column('tainted', sa.Boolean(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_computer_actions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_computer_actions'))
    )
    with op.batch_alter_table('computer_actions', schema=None) as batch_op:
        batch_op.create_index('ix_computer_action_task', ['task_id', 'sequence'], unique=False)
        batch_op.create_index('ix_computer_action_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_computer_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_computer_actions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_computer_actions_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_computer_actions_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_computer_actions_risk'), ['risk'], unique=False)
        batch_op.create_index(batch_op.f('ix_computer_actions_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_computer_actions_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_computer_actions_user_id'), ['user_id'], unique=False)

    op.create_table('computer_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.String(length=500), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('completed_actions', sa.Integer(), nullable=False),
    sa.Column('failed_actions', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('waiting_reason', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_computer_tasks_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_computer_tasks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_computer_tasks'))
    )
    with op.batch_alter_table('computer_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_computer_task_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_computer_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_computer_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_computer_tasks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computer_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_computer_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_computer_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_computer_tasks_created_at'))
        batch_op.drop_index('ix_computer_task_user_status')

    op.drop_table('computer_tasks')
    with op.batch_alter_table('computer_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_computer_actions_user_id'))
        batch_op.drop_index(batch_op.f('ix_computer_actions_task_id'))
        batch_op.drop_index(batch_op.f('ix_computer_actions_scope'))
        batch_op.drop_index(batch_op.f('ix_computer_actions_risk'))
        batch_op.drop_index(batch_op.f('ix_computer_actions_request_id'))
        batch_op.drop_index(batch_op.f('ix_computer_actions_outcome'))
        batch_op.drop_index(batch_op.f('ix_computer_actions_kind'))
        batch_op.drop_index(batch_op.f('ix_computer_actions_created_at'))
        batch_op.drop_index('ix_computer_action_user_created')
        batch_op.drop_index('ix_computer_action_task')

    op.drop_table('computer_actions')
    # ### end Alembic commands ###
